package v1beta3

import "k8s.io/kubeadm/api/scheme"

// Bar ...
type Bar struct {
	// P ...
	P string `json:"p,omitempty"`
	// Q ...
	Q string `json:"q,omitempty"`
}

// Foo ...
type Foo struct {
	scheme.TypeMeta `json:",inline"`
	// A ...
	A string `json:"a,omitempty"`
	// B ...
	B string `json:"b,omitempty"`
	// N ...
	N *Bar `json:"n,omitempty"`
}
